env: production

http:
  bind_address: "0.0.0.0:3000"
  mode: "development"
  prefix: "/api/v1"

indexer:
  enabled: true
  block_height: 151592216
  data_source:
    source_type: "neardata_api"
    neardata_api:
      base_url: "https://mainnet.neardata.xyz"
      timeout_seconds: 30
      max_requests_per_second: 8.0
      poll_interval_ms: 200
      max_retries: 3

shutdown:
  shutdown_timeout: 20s

storage:
  backend: postgres
  postgres:
    connection_string: ""
  clickhouse:
    url: ""
    user: ""
    password: ""
    database: ""

asset_worker:
  interval: 1m
  mm_supported_tokens_url: "https://bridge.chaindefuser.com/rpc"
  intents_supported_tokens_url: "https://1click.chaindefuser.com/v0/tokens"
  max_retries: 3
  timeout: 10s
